---
- hosts: all
  sudo: True
  vars_files:
    - vars.yml
    - private_vars.yml

  tasks:
    - name: Make sure current user is part of the group.
      user: name={{ user }} group={{ user_group }} state=present
  roles:
    - nginx
    - sabnzbd
    - couchpotato
      #- nzbdrone
    - sickbeard
    - transmission
    - plex
